const Questions = [
    {
        question: "How does your skin feel today?",
        answers: [
            'Tends to get shiny throughout the day',
            'A combination of shiny and dry on different areas',
            'Comfortable in summer, but dry in cooler climates',
            'Red and flaky with uneven texture',
        ],
        type: 'SingleChoice',
        inputType: 'Button',
        showAllLabel: null,
        category: 'Identifying your skin type',
        btnClass: 'btn__choice-bigger',
    },
    {
        question: 'How many hours of sun are you exposed to daily?',
        answers: [
            '1 hour',
            '2 hours',
            '3 hours',
            '4 hours',
            '5 hours',
            'More than 6 hours',
        ],
        type: 'SingleChoice',
        inputType: 'RangeSlider',
        showAllLabel: false,
        category: 'Identifying environmental stressors',
        btnClass: 'btn__choice-bigger',
    },
    {
        question: 'How much stress do you experience on a regular basis?',
        answers: [
            'None',
            'Low',
            'Medium',
            'High',
        ],
        type: 'SingleChoice',
        inputType: 'RangeSlider',
        showAllLabel: true,
        category: 'Identifying environmental stressors',
    },
    {
        question: 'Are you exposed to air pollutants?',
        answers: [
            'Yes',
            'No',
            'Uncertain',
        ],
        type: 'SingleChoice',
        inputType: 'Button',
        showAllLabel: null,
        category: 'Identifying environmental stressors',
        btnClass: 'btn__choice-bigger',
    },
    {
        question: 'Which age range do you fall into?',
        answers: [
            '< 20 years old',
            '20-25 years old',
            '26-35 years old',
            '36-45 years old',
            '> 45 years old',
        ],
        type: 'SingleChoice',
        inputType: 'Button',
        showAllLabel: null,
        category: 'Identifying key ingredients',
        btnClass: 'btn__choice-bigger',
    },
    {
        question: 'What type of skincare products are you currently using?',
        answers: [
            {label: 'Cleanser'},
            {label: 'Mask'},
            {label: 'Exfoliator'},
            {label: 'Toner'},
            {label: 'Serum'},
            {label: 'Moisturiser'},
        ],
        caption: '*Choose up to 6',
        captionClass: 'w-100 font-size-sm mb-4',
        type: 'MultipleChoice',
        lastFull: false,
        maxChoose: 6,
        lastDisableForAll: false,
        category: 'Identifying key ingredients',
        btnClass: 'btn__choice-bigger',
    },
    {
        question: 'What is your top skin concern?',
        caption: '*Choose 1',
        captionClass: 'w-100 font-size-sm mb-0',
        answers: [
            'Clogged or enlarged pores',
            'Blemishes or acne',
            'Excess oil',
            'Scarring or uneven skin texture',
            'Redness',
            'Dryness and dehydration',
            'Fine lines or wrinkles',
            'Dark spots or hyperpigmentation',
            'Dullness or uneven skin tone',
        ],
        type: 'SingleChoice',
        inputType: 'Button',
        showAllLabel: null,
        category: 'Identifying key ingredients',
        btnClass: 'btn__choice-medium',
    },
];

export default Questions;
